### ISSUE TITLE
Errors with OpenSTLinux-x11 Distro

### ISSUE THREAD

**Issue by vbursucianu** [schnitzeltony/meta-qt5-extra#73]
Steps to reproduce:
`$ mkdir openstlinux-4.19-thud-mp1-19-10-09 `
`$ cd openstlinux-4.19-thud-mp1-19-10-09`
`$ repo init -u https://github.com/STMicroelectronics/oe-manifest.git -b refs/tags/openstlinux-4.19-thud-mp1-19-10-09`
`$ repo sync`
`$ DISTRO=openstlinux-x11 MACHINE=stm32mp1 source layers/meta-st/scripts/envsetup.sh`
Accept the Eula Terms then:
`$ bitbake-layers layerindex-fetch meta-qt5-extra`
`$ bitbake-layers show-layers `

This should look like this::
```
NOTE: Starting bitbake server...
layer                 path                                      priority
==========================================================================
meta-python           /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-python  7
meta-oe               /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-oe  6
meta-oe               /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-oe  6
meta-gnome            /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-gnome  7
meta-xfce             /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-xfce  7
meta-initramfs        /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-initramfs  8
meta-multimedia       /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-multimedia  6
meta-networking       /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-networking  5
meta-webserver        /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-webserver  6
meta-filesystems      /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-filesystems  6
meta-perl             /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-perl  6
meta-python           /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-python  7
meta-st-stm32mp       /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-st/meta-st-stm32mp  6
meta-qt5              /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-qt5  7
meta-st-openstlinux   /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-st/meta-st-openstlinux  5
meta                  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta  5
meta-qt5-extra        /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra  20
```
Make sure the repos are checked out with <refs/tags/openstlinux-4.19-thud-mp1-19-10-09> if possible.
Branches:
```
project layers/openembedded-core/meta-qt5-extra/   branch origin/master
project layers/meta-qt5/                        branch github/master
project layers/meta-st/meta-st-openstlinux/     branch refs/tags/openstlinux-4.19-thud-mp1-19-10-09
project layers/meta-openembedded/               branch refs/tags/openstlinux-4.19-thud-mp1-19-10-09
project layers/meta-st/meta-st-stm32mp/         branch refs/tags/openstlinux-4.19-thud-mp1-19-10-09
project layers/meta-st/scripts/                 branch refs/tags/openstlinux-4.19-thud-mp1-19-10-09
project layers/openembedded-core/               branch refs/tags/openstlinux-4.19-thud-mp1-19-10-09
project layers/meta-timesys/                    branch refs/tags/openstlinux-4.19-thud-mp1-19-10-09
project layers/openembedded-core/bitbake/       branch refs/tags/openstlinux-4.19-thud-mp1-19-10-09
```
I configured the plasma-mobile into <VIRTUAL-RUNTIME_graphical_init_manager> 
`$ vi ../layers/meta-st/meta-st-openstlinux/conf/distro/openstlinux-x11.conf`
```
require include/st-default-distro-rules.inc
require include/st-default-distro-providers.inc
require include/openstlinux.inc

DISTRO = "openstlinux-x11"
DISTRO_NAME = "ST OpenSTLinux - X11 - (A Yocto Project Based Distro)"
TARGET_VENDOR = "-openstlinux_x11"
SDK_VENDOR = "-openstlinux_x11_sdk"

DISTRO_FEATURES_append = " opengl"
DISTRO_FEATURES_append = " gplv3 qt5 kde"
VIRTUAL-RUNTIME_graphical_init_manager = "plasma-mobile"
```
I launch my build with:
`$ bitbake -k st-example-image-x11`

I endup having 7 errors witch 6 are from the layer meta-qt-extra that is compatible with thud:
```
Summary: 7 tasks failed:
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/plasma/tier1/kdecoration/kdecoration.bb:do_configure
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/kf5/tier1/kplotting/kplotting.bb:do_configure
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/kf5/tier1/kitemviews/kitemviews.bb:do_configure
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/kf5/tier1/sonnet/sonnet.bb:do_configure
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/plasma/untier/libkscreen/libkscreen.bb:do_configure
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-qt5/recipes-qt/qt5/qtwayland_git.bb:do_configure
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/kf5/tier2/kfilemetadata/kfilemetadata.bb:do_compile
Summary: There was 1 WARNING message shown.
Summary: There were 8 ERROR messages shown, returning a non-zero exit code.
```
Some details:
1) kdecoration.bb:do_configure log shows:
```
|   The following configuration files were considered but not accepted:
|
|     /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/build-openstlinuxx11-stm32mp1/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-openstlinux_x11-linux-gnueabi/kdecoration/5.16.5-r0/recipe-sysroot/usr/lib/cmake/Qt5/Qt5Config.cmake, version: 5.11.3
|     /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/build-openstlinuxx11-stm32mp1/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-openstlinux_x11-linux-gnueabi/kdecoration/5.16.5-r0/recipe-sysroot-native/usr/lib/cmake/Qt5/Qt5Config.cmake, version: 5.11.3
```
2) kplotting.bb  log shows:
```
| -- The following REQUIRED packages have not been found:
|
|  * Qt5UiPlugin
|    Required to build Qt Designer plugins
```
3) sonnet.bb  log shows:
```
| -- The following REQUIRED packages have not been found:
|
|  * Qt5UiPlugin
|    Required to build Qt Designer plugins
```
4) libkscreen.bb
```
|   The following configuration files were considered but not accepted:
|
|     /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/build-openstlinuxx11-stm32mp1/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-openstlinux_x11-linux-gnueabi/libkscreen/5.16.5-r0/recipe-sysroot/usr/lib/cmake/Qt5/Qt5Config.cmake, version: 5.11.3
|     /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/build-openstlinuxx11-stm32mp1/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-openstlinux_x11-linux-gnueabi/libkscreen/5.16.5-r0/recipe-sysroot-native/usr/lib/cmake/Qt5/Qt5Config.cmake, version: 5.11.3
```
5) qtwayland_git.bb:
```
| ERROR: Feature 'xcomposite-glx' was enabled, but the pre-condition 'features.wayland-client && features.opengl && !features.opengles2 && features.xlib && libs.xcomposite && libs.glx' failed.
|
| ERROR: Feature 'xcomposite-glx' was enabled, but the pre-condition 'features.wayland-server && features.opengl && !features.opengles2 && libs.xcomposite && libs.glx' failed.
```
6) kfilemetadata :
```
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/build-openstlinuxx11-stm32mp1/tmp-glibc/work/cortexa7t2hf-neon-vfpv4-openstlinux_x11-linux-gnueabi/kfilemetadata/5.62.0-r0/temp/log.do_compile.11046)
```

Anyone can help me? Thanks

**Comment by schnitzeltony** [comment]
Have to ask for more information:

1. Exact revisions of your layer (branch/commits). Please drop the build configuration seen on console when running 'bitbake -k st-example-image-x11'
2. Your local.conf (you can upload it here by renaming it local.conf -> local.conf.log)
3. Same for bblayers.conf

After that I will try to reproduce your set-up steps and see what I get...

**Comment by schnitzeltony** [comment]
Looked in your logs again: Please try thud branch for meta-qt5-extra

I know your layer.conf in master says it is still compatible to thud but that does not seem to be true any more so I corrected that [1]

[1] https://github.com/schnitzeltony/meta-qt5-extra/commit/9c6b7ee064ee0241ad3aef6bc8c0be5adb6eed7c

**Comment by vbursucianu** [comment]
Hi, thanks for looking into this issue,
Here is my configuration seen on my console:
```
 $ bitbake -k st-example-image-x11                  NOTE: Started PRServer with DBfile: /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/build-openstlinuxx11-stm32mp1/cache/prserv.sqlite3, IP: 127.0.0.1, PORT: 37855, PID: 29683
Parsing recipes: 100% |#############| Time: 0:00:42Parsing of 2833 .bb files complete (0 cached, 2833 parsed). 3876 targets, 83 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
Build Configuration:
BB_VERSION           = "1.40.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-openstlinux_x11-linux-gnueabi"
MACHINE              = "stm32mp1"
DISTRO               = "openstlinux-x11"
DISTRO_VERSION       = "2.6-snapshot-20191012"
TUNE_FEATURES        = "arm armv7ve vfp thumb neon vfpv4 callconvention-hard cortexa7"
TARGET_FPU           = "hard"
DISTRO_CODENAME      = "thud"
ACCEPT_EULA_stm32mp1 = "1"
GCCVERSION           = "8.%"
PREFERRED_PROVIDER_virtual/kernel = "linux-stm32mp"meta-python
meta-oe
meta-oe
meta-gnome
meta-xfce
meta-initramfs
meta-multimedia
meta-networking
meta-webserver
meta-filesystems
meta-perl
meta-python          = "refs/tags/openstlinux-4.19-thud-mp1-19-10-09:9b3b907f30b0d5b92d58c7e68289184fda733d3e"
meta-st-stm32mp      = "heads/refs/tags/openstlinux-4.19-thud-mp1-19-10-09:d8cbac759e1275b1a27d4ba38b64a0d83d0e8c9f"
meta-qt5             = "heads/github/thud:1520d5b2b2beec5e1c3209d3178219e93ef08bca"
meta-st-openstlinux  = "heads/refs/tags/openstlinux-4.19-thud-mp1-19-10-09:ee276cb390d7dd1175d386ba2bfd384c1b206808"
meta                 = "refs/tags/openstlinux-4.19-thud-mp1-19-10-09:d3d3f443039b03f1200a14bfe99f985592632018"
meta-qt5-extra       = "heads/origin/thud:09ae5e345a5e3559e6237b93edf956cfd52e4dcf"
```
The build still fails even on the thud branch from the layer meta-qt5 and meta-qt5-extra.
Looks like the errors are the same:
```
# This file is your local configuration file and is where all local user settings
# are placed. The comments in this file give some guide to the options a new user                     # to the system might want to change but pretty much any configuration option can                     # be set in this file. More adventurous users can look at local.conf.extended
# which contains other examples of configuration which can be placed in this file                     # but new users likely won't need any of them initially.
#                                                  #                                                  # This file is your local configuration file and is where all local user settings                     #                                                  # This file is your local configuration file and is where all local user settings                     # are placed. The comments in this file give some guide to the options a new user                     # to the system might want to change but pretty much any configuration option can                     # be set in this file. More adventurous users can look at local.conf.extended                         # which contains other examples of configuration which can be placed in this file                     # but new users likely won't need any of them initially.                                              #                                                  # Lines starting with the '#' character are commented out and in some cases the                       # default values are provided as comments to show people example syntax. Enabling                     conf/local.conf                  1,1            Top[ns@yocto build-openstlinuxx11-stm32mp1]           $ cat conf/local.conf
#
# This file is your local configuration file and is where all local user settings
# are placed. The comments in this file give some guide to the options a new user
# to the system might want to change but pretty much any configuration option can
# be set in this file. More adventurous users can look at local.conf.extended
# which contains other examples of configuration which can be placed in this file
# but new users likely won't need any of them initially.
#
# Lines starting with the '#' character are commented out and in some cases the
# default values are provided as comments to show people example syntax. Enabling
# the option is a question of removing the # character and making any change to the
# variable as required.

#
# Machine Selection
#
# You need to select a specific machine to target the build with. There are a selection
# of emulated machines available which can boot and run in the QEMU emulator:
#
#MACHINE ?= "qemuarm"
#MACHINE ?= "qemuarm64"
#MACHINE ?= "qemumips"
#MACHINE ?= "qemumips64"
#MACHINE ?= "qemuppc"
#MACHINE ?= "qemux86"
#MACHINE ?= "qemux86-64"
#
# This sets the default machine to be qemux86 if no other machine is selected:
#MACHINE ??= "qemux86"
MACHINE = "stm32mp1"

#
# Default policy config
#
# The distribution setting controls which policy settings are used as defaults.
# The default value is fine for general Yocto project use, at least initially.
# Ultimately when creating custom policy, people will likely end up subclassing
# these defaults.
#
# This sets the default distribution to be nodistro if no other distribution is selected:
#DISTRO ??= "nodistro"
DISTRO = "openstlinux-x11"

#
# Where to place downloads
#
# During a first build the system will download many different source code tarballs
# from various upstream projects. This can take a while, particularly if your network
# connection is slow. These are all stored in DL_DIR. When wiping and rebuilding you
# can preserve this directory to speed up this part of subsequent builds. This directory
# is safe to share between multiple builds on the same machine too.
#
# The default is a downloads directory under TOPDIR which is the build directory.
#
#DL_DIR ?= "${TOPDIR}/downloads"

#
# Where to place shared-state files
#
# BitBake has the capability to accelerate builds based on previously built output.
# This is done using "shared state" files which can be thought of as cache objects
# and this option determines where those files are placed.
#
# You can wipe out TMPDIR leaving this directory intact and the build would regenerate
# from these files if no changes were made to the configuration. If changes were made
# to the configuration, only shared state files where the state was still valid would
# be used (done using checksums).
#
# The default is a sstate-cache directory under TOPDIR.
#
#SSTATE_DIR ?= "${TOPDIR}/sstate-cache"

#
# Where to place the build output
#
# This option specifies where the bulk of the building work should be done and
# where BitBake should place its temporary files and output. Keep in mind that
# this includes the extraction and compilation of many applications and the toolchain
# which can use Gigabytes of hard disk space.
#
# The default is a tmp directory under TOPDIR.
#
#TMPDIR = "${TOPDIR}/tmp"


#
# Package Management configuration
#
# This variable lists which packaging formats to enable. Multiple package backends
# can be enabled at once and the first item listed in the variable will be used
# to generate the root filesystems.
# Options are:
#  - 'package_deb' for debian style deb files
#  - 'package_ipk' for ipk files are used by opkg (a debian style embedded package manager)
#  - 'package_rpm' for rpm style packages
# E.g.: PACKAGE_CLASSES ?= "package_rpm package_deb package_ipk"
# We default to ipk:
PACKAGE_CLASSES ?= "package_ipk"

#
# SDK target architecture
#
# This variable specifies the architecture to build SDK items for and means
# you can build the SDK packages for architectures other than the machine you are
# running the build on (i.e. building i686 packages on an x86_64 host).
# Supported values are i686 and x86_64
#SDKMACHINE ?= "i686"

#
# Extra image configuration defaults
#
# The EXTRA_IMAGE_FEATURES variable allows extra packages to be added to the generated
# images. Some of these options are added to certain image types automatically. The
# variable can contain the following options:
#  "dbg-pkgs"       - add -dbg packages for all installed packages
#                     (adds symbol information for debugging/profiling)
#  "dev-pkgs"       - add -dev packages for all installed packages
#                     (useful if you want to develop against libs in the image)
#  "ptest-pkgs"     - add -ptest packages for all ptest-enabled packages
#                     (useful if you want to run the package test suites)
#  "tools-sdk"      - add development tools (gcc, make, pkgconfig etc.)
#  "tools-debug"    - add debugging tools (gdb, strace)
#  "eclipse-debug"  - add Eclipse remote debugging support
#  "tools-profile"  - add profiling tools (oprofile, lttng, valgrind)
#  "tools-testapps" - add useful testing tools (ts_print, aplay, arecord etc.)
#  "debug-tweaks"   - make an image suitable for development
#                     e.g. ssh root access has a blank password
# There are other application targets that can be used here too, see
# meta/classes/image.bbclass and meta/classes/core-image.bbclass for more details.
# We default to enabling the debugging tweaks.
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"

#
# Additional image features
#
# The following is a list of additional classes to use when building images which
# enable extra features. Some available options which can be included in this variable
# are:
#   - 'buildstats' collect build statistics
#   - 'image-mklibs' to reduce shared library files size for an image
#   - 'image-prelink' in order to prelink the filesystem image
# NOTE: if listing mklibs & prelink both, then make sure mklibs is before prelink
# NOTE: mklibs also needs to be explicitly enabled for a given image, see local.conf.extended
USER_CLASSES ?= "buildstats image-mklibs image-prelink"


#
# Runtime testing of images
#
# The build system can test booting virtual machine images under qemu (an emulator)
# after any root filesystems are created and run tests against those images. It can also
# run tests against any SDK that are built. To enable this uncomment these lines.
# See classes/test{image,sdk}.bbclass for further details.
#IMAGE_CLASSES += "testimage testsdk"
#TESTIMAGE_AUTO_qemuall = "1"

#
# Interactive shell configuration
#
# Under certain circumstances the system may need input from you and to do this it
# can launch an interactive shell. It needs to do this since the build is
# multithreaded and needs to be able to handle the case where more than one parallel
# process may require the user's attention. The default is iterate over the available
# terminal types to find one that works.
#
# Examples of the occasions this may happen are when resolving patches which cannot
# be applied, to use the devshell or the kernel menuconfig
#
# Supported values are auto, gnome, xfce, rxvt, screen, konsole (KDE 3.x only), none
# Note: currently, Konsole support only works for KDE 3.x due to the way
# newer Konsole versions behave
#OE_TERMINAL = "auto"
# By default disable interactive patch resolution (tasks will just fail instead):
PATCHRESOLVE = "noop"

#
# Disk Space Monitoring during the build
#
# Monitor the disk space during the build. If there is less that 1GB of space or less
# than 100K inodes in any key build location (TMPDIR, DL_DIR, SSTATE_DIR), gracefully
# shutdown the build. If there is less that 100MB or 1K inodes, perform a hard abort
# of the build. The reason for this is that running completely out of space can corrupt
# files and damages the build in ways which may not be easily recoverable.
# It's necesary to monitor /tmp, if there is no space left the build will fail
# with very exotic errors.
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    ABORT,${TMPDIR},100M,1K \
    ABORT,${DL_DIR},100M,1K \
    ABORT,${SSTATE_DIR},100M,1K \
    ABORT,/tmp,10M,1K"

#
# Shared-state files from other locations
#
# As mentioned above, shared state files are prebuilt cache data objects which can
# used to accelerate build time. This variable can be used to configure the system
# to search other mirror locations for these objects before it builds the data itself.
#
# This can be a filesystem directory, or a remote url such as http or ftp. These
# would contain the sstate-cache results from previous builds (possibly from other
# machines). This variable works like fetcher MIRRORS/PREMIRRORS and points to the
# cache locations to check for the shared objects.
# NOTE: if the mirror uses the same structure as SSTATE_DIR, you need to add PATH
# at the end as shown in the examples below. This will be substituted with the
# correct path within the directory structure.
#SSTATE_MIRRORS ?= "\
#file://.* http://someserver.tld/share/sstate/PATH;downloadfilename=PATH \n \
#file://.* file:///some/local/dir/sstate/PATH"


#
# Qemu configuration
#
# By default qemu will build with a builtin VNC server where graphical output can be
# seen. The two lines below enable the SDL backend too. By default libsdl2-native will
# be built, if you want to use your host's libSDL instead of the minimal libsdl built
# by libsdl2-native then uncomment the ASSUME_PROVIDED line below.
PACKAGECONFIG_append_pn-qemu-native = " sdl"
PACKAGECONFIG_append_pn-nativesdk-qemu = " sdl"
#ASSUME_PROVIDED += "libsdl2-native"

# =========================================================================
#   ST SPecific
# =========================================================================
#
# CONF_VERSION is increased each time build/conf/ changes incompatibly and is used to
# track the version of this file when it was generated. This can safely be ignored if
# this doesn't mean anything to you.
CONF_VERSION = "1"

# Set GLIBC_GENERATE_LOCALES to the locales you wish to generate should you not
# wish to perform the time-consuming step of generating all LIBC locales.
# NOTE: If removing en_US.UTF-8 you will also need to uncomment, and set
# appropriate value for IMAGE_LINGUAS.
# WARNING: this may break localisation!
GLIBC_GENERATE_LOCALES = "en_GB.UTF-8 en_US.UTF-8"
IMAGE_LINGUAS ?= "en-gb"

# Additional image generation features
#
# The following is a list of classes to import to use in the generation of images
# currently an example class is image_types_uboot
# IMAGE_CLASSES = " image_types_uboot"

# Support of devshell
INHERIT += "devshell"

# Remove the old image before the new one generated to save disk space
RM_OLD_IMAGE = "1"

# Nice debug data
INHERIT += "buildhistory"
BUILDHISTORY_COMMIT = "1"

# Clean up working directory after build
INHERIT += "rm_work"

# To generate debug image with all symbol
#IMAGE_GEN_DEBUGFS = "1"

# force the usage of debian package
PACKAGE_CLASSES = "package_deb"

# To enable archiver for recipes that are configured
#ST_ARCHIVER_ENABLE = "1"

# Setup environment for builds binary reproducibility
INHERIT += "reproducible_build"

# Setup eSDK
SDK_EXT_TYPE="minimal"
SDK_INCLUDE_TOOLCHAIN="1"

# Enable PR server to avoid version-going-backward issue
PRSERV_HOST = "localhost:0"

# =========================================================================
# Configure STM32MP default version to github
# =========================================================================
#STM32MP_SOURCE_SELECTION_pn-linux-stm32mp = "github"
#STM32MP_SOURCE_SELECTION_pn-optee-os-stm32mp = "github"
#STM32MP_SOURCE_SELECTION_pn-tf-a-stm32mp = "github"
#STM32MP_SOURCE_SELECTION_pn-u-boot-stm32mp = "github"

# =========================================================================
# Set EULA acceptance
# =========================================================================
ACCEPT_EULA_stm32mp1 = "1"
```
And my bblayer.conf:
```
# LAYER_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
LCONF_VERSION = "7"

BBPATH = "${TOPDIR}"
BBFILES ?= ""
OEROOT := "${@os.path.abspath(os.path.dirname(d.getVar('FILE')) + '/../..')}"

#--------------------------
# Layers var definition for buildsystem
#
OPENEMBEDDED = "${OPENEMBEDDED_NON_REMOVABLE}"

OPENEMBEDDED_NON_REMOVABLE = "${OEROOT}/layers/openembedded-core/meta"

POKY  = "${POKY_NON_REMOVABLE}"
POKY += "${OEROOT}/layers/poky/meta-yocto-bsp"

POKY_NON_REMOVABLE  = "${OEROOT}/layers/poky/meta"
POKY_NON_REMOVABLE += "${OEROOT}/layers/poky/meta-yocto"

#--------------------------
#
BASELAYERS ?= " \
    ${OEROOT}/layers/meta-openembedded/meta-oe \
    ${OEROOT}/layers/meta-openembedded/meta-gnome \    ${OEROOT}/layers/meta-openembedded/meta-xfce \
    ${OEROOT}/layers/meta-openembedded/meta-initramfs \
    ${OEROOT}/layers/meta-openembedded/meta-multimedia \
    ${OEROOT}/layers/meta-openembedded/meta-networking \
    ${OEROOT}/layers/meta-openembedded/meta-webserver \
    ${OEROOT}/layers/meta-openembedded/meta-filesystems \
    ${OEROOT}/layers/meta-openembedded/meta-perl \
    ${OEROOT}/layers/meta-openembedded/meta-python \
"

BBLAYERS_NON_REMOVABLE ?= " \
    ${@'${OPENEMBEDDED_NON_REMOVABLE}' if os.path.isfile('${OEROOT}/layers/openembedded-core/meta/conf/layer.conf') else '${POKY_NON_REMOVABLE}'} \
  "

BSPLAYER ?= " \
    ${@'${OEROOT}/layers/meta-st/meta-st-cannes2' if os.path.isfile('${OEROOT}/layers/meta-st/meta-st-cannes2/conf/layer.conf') else ''} \
    ${@'${OEROOT}/layers/meta-st/meta-st-stm32mp' if os.path.isfile('${OEROOT}/layers/meta-st/meta-st-stm32mp/conf/layer.conf') else ''} \
    "

ADDONSLAYERS = ""
# linaro
ADDONSLAYERS += "${@'${OEROOT}/layers/meta-linaro/meta-linaro' if os.path.isfile('${OEROOT}/layers/meta-linaro/meta-linaro/conf/layer.conf') else ''}"
ADDONSLAYERS += "${@'${OEROOT}/layers/meta-linaro/meta-linaro-toolchain' if os.path.isfile('${OEROOT}/layers/meta-linaro/meta-linaro-toolchain/conf/layer.conf') else ''}"
ADDONSLAYERS += "${@'${OEROOT}/layers/meta-openembedded/meta-networking' if os.path.isfile('${OEROOT}/layers/meta-linaro/meta-linaro/conf/layer.conf') else ''}"

# Qt5
ADDONSLAYERS += "${@'${OEROOT}/layers/meta-qt5' if os.path.isfile('${OEROOT}/layers/meta-qt5/conf/layer.conf') else ''}"

# Security layer
ADDONSLAYERS += " \
    ${@'${OEROOT}/layers/meta-security \
    ${OEROOT}/layers/meta-security/meta-tpm \
    ${OEROOT}/layers/meta-openembedded/meta-perl \
    ${OEROOT}/layers/meta-openembedded/meta-filesystems' \
    if os.path.isfile('${OEROOT}/layers/meta-security/conf/layer.conf') else ''} \
    "

# specific to framework
FRAMEWORKLAYERS += "${@'${OEROOT}/layers/meta-st/meta-st-openstlinux' if os.path.isfile('${OEROOT}/layers/meta-st/meta-st-openstlinux/conf/layer.conf') else ''}"

# add BSP layer
BBLAYERS += " \
  ${BASELAYERS} \
  ${BSPLAYER} \
  ${ADDONSLAYERS} \
  ${FRAMEWORKLAYERS} \
  ${@'${OPENEMBEDDED}' \
  if \
  os.path.isfile('${OEROOT}/layers/openembedded-core/meta/conf/layer.conf') \
  else \
  '${POKY}'} \
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra \
  "
# BSP dependencies"
BBLAYERS =+ "/home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-oe"
BBLAYERS =+ "/home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-openembedded/meta-python"
[ns@yocto build-openstlinuxx11-stm32mp1]
```

**Comment by vbursucianu** [comment]
The build failed with those errors when using the thud branch for meta-qt5 and meta-qt5-extra:
```
NOTE: Tasks Summary: Attempted 11464 tasks of which 11457 didn't need to be rerun and 7 failed.
NOTE: Writing buildhistory
Summary: 7 tasks failed:
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/kf5/tier1/kitemviews/kitemviews.bb:do_configure
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/kf5/tier1/sonnet/sonnet.bb:do_configure
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/kf5/tier2/kfilemetadata/kfilemetadata.bb:do_compile
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/kf5/tier1/kplotting/kplotting.bb:do_configure
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/plasma/tier1/kdecoration/kdecoration.bb:do_configure
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/openembedded-core/meta-qt5-extra/recipes-kde/plasma/untier/libkscreen/libkscreen.bb:do_configure
  /home/ns/Documents/stm32/distribution-package/openstlinux-4.19-thud-mp1-19-10-09/layers/meta-qt5/recipes-qt/qt5/qtwayland_git.bb:do_configure
Summary: There were 8 ERROR messages shown, returning a non-zero exit code.
[ns@yocto build-openstlinuxx11-stm32mp1]
```
Looks like the same issues

**Comment by vbursucianu** [comment]
Hi schnitzeltony,
Any success on solving this issue? Thanks :)

**Comment by schnitzeltony** [comment]
Sorry but I do have the resources currently:

* am working on gnome patches for meta-openembedded
* have one build machine at home only

One hint maybe helpful:
The last error is meta-qt5*s qtwayland. Am not sure but do you have wayland in your DISTRO_FEATURES?

To check run
bitbake -e | grep ^DISTRO_FEATURES

Maybe you can post the result here.

**Comment by schnitzeltony** [comment]
No activity for long time - close it
